#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout

offers:
    path:     /carrieres/offers
    controller: App\Controller\Carrieres\OfferController::index